name: Daily Greeting

on:
  schedule:
    - cron: '0 0 * * *'  # Este cronograma es para ejecutar el script a medianoche UTC todos los días

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Actualizado a una versión hipotética que soporta Node.js 16
    - uses: actions/setup-python@v3  # Actualizado a una versión hipotética que soporta Node.js 16
      with:
        python-version: '3.x'

    - name: Run greeting script
      run: python greet.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "dgarzon11@gmail.com"
        git config --global user.name "dgarzon11"
        git add greetings.txt
        git commit -m "Add today's greeting" || echo "No changes to commit"
        git push
